#!/usr/bin/with-contenv bash
# shellcheck shell=bash

set -o errexit
set -o pipefail
set -o nounset
if [[ "${TRACE-0}" == "1" ]]; then set -o xtrace; fi

exec \
    s6-setuidgid abc java -Djava.awt.headless=true -jar /app/JDownloader.jar