# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Check baseimage has been updated

on:
  schedule:
    - cron: '5 4 * * 1' # At 04:05 on Monday

env:
  REGISTRY_GITHUB: ghcr.io
  IMAGE_NAME: ${{ github.repository }}
  BUILD_PLATFORMS: "linux/amd64,linux/arm64/v8"

jobs:
  check-baseimage:
    runs-on: ubuntu-latest
    timeout-minutes: 20
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - id: string_lower_case
        uses: ASzc/change-string-case-action@v2
        with:
          string: ${{ env.IMAGE_NAME }}

      - name: Docker Image Update Checker
        id: baseupdatecheck
        uses: lucacome/docker-image-update-checker@v1
        with:
          base-image: library/openjdk:11-jre-slim
          image: ${{ steps.string_lower_case.outputs.lowercase }}:latest

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
        if: steps.baseupdatecheck.outputs.needs-updating == 'true'

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
        if: steps.baseupdatecheck.outputs.needs-updating == 'true'
      
      - name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
        if: steps.baseupdatecheck.outputs.needs-updating == 'true'

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1 
        with:
          registry: ${{ env.REGISTRY_GITHUB }}
          username: ${{ github.actor }}
          password: ${{ secrets.TOKEN }}
        if: steps.baseupdatecheck.outputs.needs-updating == 'true'

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v3
        with:
          images: ${{ env.IMAGE_NAME }},${{ env.REGISTRY_GITHUB }}/${{ env.IMAGE_NAME }}
          tags: |
            type=ref,event=branch
            type=raw,value=latest,enable=${{ github.ref == format('refs/heads/{0}', github.event.repository.default_branch) }}
          flavor: |
            latest=auto
            prefix=
            suffix=
        if: steps.baseupdatecheck.outputs.needs-updating == 'true'

      - name: Build and push Docker image (WITHOUT ffmpeg)
        uses: docker/build-push-action@v2
        with:
          context: .
          platforms: ${{ env.BUILD_PLATFORMS }}
          pull: true
          file: Dockerfile
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
        if: steps.baseupdatecheck.outputs.needs-updating == 'true'

      - name: Extract metadata (tags, labels) for Docker
        id: meta_ffmpeg
        uses: docker/metadata-action@v3
        with:
          images: ${{ env.IMAGE_NAME }},${{ env.REGISTRY_GITHUB }}/${{ env.IMAGE_NAME }}
          tags: |
            type=ref,event=branch
            type=raw,value=latest,enable=${{ github.ref == format('refs/heads/{0}', github.event.repository.default_branch) }}
          flavor: |
            latest=auto
            prefix=
            suffix=-ffmpeg
        if: steps.baseupdatecheck.outputs.needs-updating == 'true'

      - name: Build and push Docker image (WITH ffmpeg)
        uses: docker/build-push-action@v2
        with:
          context: .
          platforms: ${{ env.BUILD_PLATFORMS }}
          pull: true
          file: Dockerfile-ffmpeg
          push: true
          tags: ${{ steps.meta_ffmpeg.outputs.tags }}
          labels: ${{ steps.meta_ffmpeg.outputs.labels }}
        if: steps.baseupdatecheck.outputs.needs-updating == 'true'

      - name: Docker Hub Description
        uses: peter-evans/dockerhub-description@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
          repository: ${{ env.IMAGE_NAME }}
          readme-filepath: ./README.md
        if: steps.baseupdatecheck.outputs.needs-updating == 'true'
